# Site
name: 'Working with Jekyll'
description: 'JWorking with Jekyll'
baseurl: '/working-with-jekyll'

include: ["_pages"]
#permalink: /:title/

# Plugins
#   - jekyll-feed
plugins: 
#  - jekyll-sitemap
#  - jekyll-paginate
#  - jekyll-seo-tag
 
# Defaults
defaults:

  # all posts
  - scope:
      path: "_posts"
    values:
      layout: post
      
  # all pages
  - scope:
      path: "_pages"
    values:
      layout: page

#
collections_dir: collections
collections:
  services:
  teams:
  pages:
  customers:
  portfolio:

# Syntax
markdown: kramdown
highlighter: rouge

# Pagination
#paginate: 20

# Exclude metadata and development time dependencies (like Grunt plugins)
exclude: [README.markdown, package.json, grunt.js, Gruntfile.js, Gruntfile.coffee, node_modules]

#
sass:
    sass_dir: /assets/css
    style:    compressed
